config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users

  resources :mountains 
  # do 
  #   resources :review
  # end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mountain.rb
class Mountain < ApplicationRecord
    # validates :ability, inclusion: { in: %w(beginner intermediate advanced),
    # message: "%{value} is not valid, please enter: beginner, intermediate, advanced" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :mountain
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :ability])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @mountains = Mountain.all
    @users_mountains = []

    @mountains.each do |mountain|
      if mountain.ability == current_user.ability
        @users_mountains << mountain
      end
    end
  end
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  before_action :set_mountain, except: [:create, :new, :index]

  def index
    @mountains = Mountain.all
    
  end

  def show
  end

  def new
    @mountain = Mountain.new
  end

  def edit
  end

  def update

    if @mountain.update(mountain_params)
      redirect_to mountains_path
    else
      render :edit
    end
  end

  def create
    @mountain = Mountain.new(mountain_params)

    if @mountain.save
      redirect_to mountains_path
    else 
      render :new
    end
  end

  def destroy
    @mountain.destroy
    flash[:notice] = 'Mountain Deleted!'
    redirect_to mountains_path
  end

  private

  def mountain_params
    params.require(:mountain).permit(:name, :elevation, :latitude, :longitude, :ability)
  end

  def set_mountain
    @mountain = Mountain.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mountains_helper.rb
module MountainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1> <%= current_user.name %> Mountains </h1>
<p><%= link_to 'Add New Mountain', new_mountain_path %></p>
<% @users_mountains.each do |mountain| %>
    <h3><%= mountain.name %></h3>
    <h3>Elevation: <%= mountain.elevation %></h3>
    <h3>Lat/Long: <%= mountain.latitude %>, <%= mountain.longitude %></h3>
    <h3>Difficulty rating: <%= mountain.ability %></h3>
    <%= link_to 'Show Mountain', mountain_path(mountain) %>
    <%= link_to 'Edit Mountain', edit_mountain_path(mountain) %>
    <%= link_to 'Delete Mountain', mountain_path(mountain), method: :delete %>

<% end %>

app/views/layouts/_nav.html.erb
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">JavaScript</a></li>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ascender</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo">Ascender</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "Mountains", mountains_path %></li>
          <% if current_user %>
            <li><%= link_to "User Home", root_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/mountains/edit.html.erb
<h1> Edit Mountain </h1>
<%= form_for @mountain do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :elevation %>
  <%= f.number_field :elevation %>

  <%= f.label :latitude %>
  <%= f.number_field :latitude, class: :text_field, step: :any %>

  <%= f.label :longitude %>
  <%= f.number_field :longitude, class: :text_field, step: :any %>

  <%= f.label :ability %>
  <%= f.text_field :ability %>

  <%= f.submit %>
<% end %>

app/views/mountains/index.html.erb
<h1> Mountains </h1>
<p><%= link_to 'Add New Mountain', new_mountain_path %></p>


  <div class="row">
    <% @mountains.each do |mountain| %>
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image">
          <img src=<%= image_path('<%= #{mountain.name}%>.jpg') %> />
          <span class="card-title"><%= mountain.name %></span>
          <a class="btn-floating halfway-fab waves-effect waves-light blue right">
          <i class="material-icons right">add<%= link_to " ", mountain_path(mountain) %></i></a>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col s12 m3">
      <div class="card">
        <div class="card-image" > 
          <img src=<%= image_path('Everest.jpg') %> />
         <span class="card-title">Card Title</span>
          <a class="btn-floating halfway-fab waves-effect waves-light red right"><i class="material-icons right">add</i></a>
        </div>
        
        
      </div>
    </div>
  </div>

app/views/mountains/new.html.erb
<h1> New Mountain </h1>
<%= form_for @mountain do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :elevation %>
  <%= f.number_field :elevation %>

  <%= f.label :latitude %>
  <%= f.number_field :latitude, class: :text_field, step: :any %>

  <%= f.label :longitude %>
  <%= f.number_field :longitude, class: :text_field, step: :any %>

  <%= f.label :rating %>
  <%= f.number_field :rating %>

  <%= f.submit %>
<% end %>

app/views/mountains/show.html.erb
<h1> Mountain detail </h1>
    <h3><%= @mountain.name %></h3>
    <h3>Elevation: <%= @mountain.elevation %></h3>
    <h3>Lat/Long: <%= @mountain.latitude %> - <%= @mountain.longitude %></h3>
    <h3>Difficulty rating: <%= @mountain.ability %></h3>

    <%= link_to 'Show Mountain', mountain_path(@mountain) %>
    <%= link_to 'Edit Mountain', edit_mountain_path(@mountain) %>
    <%= link_to 'Delete Mountain', mountain_path(@mountain), method: :delete %>
    <%= link_to 'Back to Mountains', mountains_path %>

app/views/users/show.html.erb
<h1> <%= current_user.name %> Mountains </h1>
<p><%= link_to 'Add New Mountain', new_mountain_path %></p>
<% @users_mountains.each do |mountain| %>
    <h3><%= mountain.name %></h3>
    <h3>Elevation: <%= mountain.elevation %></h3>
    <h3>Lat/Long: <%= mountain.latitude %>, <%= mountain.longitude %></h3>
    <h3>Difficulty rating: <%= mountain.ability %></h3>
    <%= link_to 'Show Mountain', mountain_path(mountain) %>
    <%= link_to 'Edit Mountain', edit_mountain_path(mountain) %>
    <%= link_to 'Delete Mountain', mountain_path(mountain), method: :delete %>

<% end %>